# Generated by Django 3.2.5 on 2021-08-01 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=49, unique=True)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registaration_guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=15)),
                ('code', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('info', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='Caljan/static/tables')),
            ],
        ),
        migrations.CreateModel(
            name='User_guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=69)),
                ('b_date', models.DateField(null=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('session_password', models.CharField(max_length=16, unique=True)),
                ('role', models.IntegerField(default=2)),
                ('bonus_amount', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=49)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Caljan/static/image/menu')),
                ('food_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caljan.food_class')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caljan.user_guest')),
            ],
        ),
    ]
