# Generated by Django 3.2.5 on 2021-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_class',
            name='category_photo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
