# Generated by Django 3.2.5 on 2021-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0002_food_class_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_class',
            name='name',
            field=models.CharField(max_length=49),
        ),
    ]
