# Generated by Django 3.2.5 on 2021-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0003_alter_food_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
