# Generated by Django 3.2.5 on 2021-08-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0005_alter_menu_food_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='photo',
        ),
    ]
