# Generated by Django 3.2.5 on 2021-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0007_auto_20210801_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_num',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
