# Generated by Django 3.2.5 on 2021-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0008_alter_tables_table_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_id', models.IntegerField(default=models.AutoField(primary_key=True, serialize=False))),
                ('workshop_name', models.CharField(default='Кухня', max_length=100)),
            ],
        ),
    ]
