# Generated by Django 3.2.5 on 2021-08-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0010_menu_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='workshop',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
