# Generated by Django 3.2.5 on 2021-08-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0011_menu_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caljan.workshop'),
        ),
    ]
