# Generated by Django 3.2.5 on 2021-08-06 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0012_alter_menu_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_shedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_work_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField()),
                ('approved', models.BooleanField(default=None)),
                ('comment', models.CharField(default='', max_length=200)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caljan.user_guest')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caljan.tables')),
            ],
        ),
    ]
