# Generated by Django 3.2.5 on 2021-08-06 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0013_admin_shedule_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_shedule',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admin_shedule',
            name='end_work_time',
            field=models.TimeField(default=datetime.time(0, 2), null=True),
        ),
        migrations.AddField(
            model_name='admin_shedule',
            name='work_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='shedule',
            name='visit_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='admin_shedule',
            name='start_work_time',
            field=models.TimeField(default=datetime.time(0, 1), null=True),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='visit_time',
            field=models.TimeField(default=datetime.time(1, 0), null=True),
        ),
    ]
