# Generated by Django 3.2.5 on 2021-08-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0014_auto_20210806_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=36, unique=True)),
                ('password', models.CharField(max_length=36, unique=True)),
                ('tg_chat_id', models.IntegerField(default=None)),
            ],
        ),
    ]
