# Generated by Django 3.2.5 on 2021-08-07 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caljan', '0015_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_shedule',
            name='work_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='visit_day',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
